language: java
jdk:
- oraclejdk8
install:
- curl -sS -O https://raw.githubusercontent.com/ExLibrisGroup/Rosetta.dps-sdk-projects/master/5.0.1/dps-sdk-deposit/lib/dps-sdk-5.0.1.jar
- mvn install:install-file -Dfile=dps-sdk-5.0.1.jar -DgroupId=com.exlibris.dps -DartifactId=dps-sdk
  -Dversion=5.0.1 -Dpackaging=jar
script:
- mvn clean install
deploy:
  provider: releases
  api_key:
    secure: RQTxfA1OZRu6eLJ8GoeUtX+jeOgvL6nWfTNOwVMATcWttbGEh4Vm+N8KJ5770HgZdG/+C96vrLMTE7PaFN8X4MBtwqvb9V3QBSCrJ40e/Vwolp+QwSdOUJTMDPCo5S3f5TvLWR1Wf0hbpp7/EpZ7usFv/eFZ6hvUccoWQEr/PtQIqV07Ninz/XuZviYgXr45lRvHPRhv8mvJXoko+CwOLwp8M5RjfQ+rSRwXyaDvTMHq2G32J7vbYZNN6+sKvCOd53g1OJ0/eh+qkYfzzN5l0pFajBxk8/13gByv9FmnVacwoKYTeWV7j+wJdAU0rX9rDD6tXAeRrdh0/VvvAhs5bFFXIwxj9nCv2B32TMbe7PxGtj3K9ZMmRTvJXpYMGzqSPTaMGJBQqBjDasfFgACIe0L/Do5BMy3w/E93qnd+biccQ4AMYbZtgp91gtVmRV+XHAOfuLjWT/JOpmqjnDCs9IU/xFOMEHCvguCJXKMJfrg5mQcDTqSLQ+lwsy2WepdH74S6pbwlbrlZ8tnu2LC7TKgQGj6T1DlVj5zhbeJZm2kyaG5LnPnwxvtHiFoPR8AjqPQBMxOVlQKuDC6xDjzrT1ehwmDbmyk6/nCNcrLtTKU9f8P/IGAYb3YcJUvVDWDf0IYz/X+36csN7qM+OGXdsYoiTH8AkcuKL1qXXsRNc48=
  file: target/*.jar
  skip_cleanup: true
  on:
    tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash)
